name: emartdriver
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.2+2

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  cloud_functions: ^4.5.8
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  flutter_local_notifications:
  flutter_facebook_auth: ^5.0.11
  geoflutterfire2: ^2.3.15
  geolocator: ^9.0.2
  geocoding: ^2.1.0

  image_picker: ^1.0.5
  progress_dialog_null_safe: ^1.0.7
  provider: ^6.1.1
  url_launcher: ^6.2.1
  intl: 0.19.0
  cached_network_image: ^3.3.0
  uuid: ^3.0.7
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.1
  photo_view: ^0.14.0
  video_player: ^2.8.1
  smooth_page_indicator: ^1.1.0
  intl_phone_number_input: ^0.7.4
  pin_code_fields: ^8.0.1
  permission_handler: ^11.1.0
  easy_localization: ^3.0.3
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^1.0.0
  cupertino_icons: ^1.0.6
  flutter_native_image: ^0.0.6+1
  the_apple_sign_in: ^1.1.1
  video_compress: ^3.1.2
  location: ^5.0.3
  flutter_otp_text_field: ^1.1.1
  audioplayers: ^5.2.1
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html: ^0.14.9
  flutterflow_paginate_firestore: ^1.0.3+1
  razorpay_flutter: ^1.3.5
  flutter_stripe: ^9.6.0
  mercadopago_sdk: ^1.3.0
  paytm_allinonesdk: ^1.2.1
  flutterwave_standard: ^1.0.7
  mailer: ^6.0.1
  flutter_easyloading: ^3.0.5
  flutter_paypal_native: ^2.1.0
  zego_uikit_prebuilt_call: ^3.17.10
  zego_uikit_signaling_plugin: ^2.7.0

dependency_overrides:
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo.png
  image_dark: assets/images/app_logo.png

  android_12:
    image: assets/images/app_logo.png
    image_dark: assets/images/app_logo.png

  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - assets/flags/
    - assets/audio/

  fonts:
    - family: Poppinsb
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppinsl
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppinsm
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppinsr
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppinssb
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
